message("FindGrNrsc5Rx.cmake")

SET(GRNRSC5RX_SEARCH_PATHS
    /usr
    /usr/local
)

FIND_PATH(GRNRSC5RX_INCLUDE_DIR nrsc5_rx.h
    PATH_SUFFIXES include/nrsc5_rx include
    PATHS ${GRNRSC5RX_SEARCH_PATHS}
)

FIND_LIBRARY(GRNRSC5RX_LIBRARIES
    NAMES gnuradio-nrsc5_rx
    PATH_SUFFIXES lib lib64
    PATHS ${GRNRSC5RX_SEARCH_PATHS}
)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(GrNrsc5Rx
    REQUIRED_VARS GRNRSC5RX_INCLUDE_DIR GRNRSC5RX_LIBRARIES
)
